
# -*- coding: utf-8 -*-
"""Text_Summarization_T5_Finetuning_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1...

# Text Summarization with T5 (Fine-Tuning)

This notebook implements **Fine-Tuning of T5-Small** for text summarization.
This approach leverages Transfer Learning to solve issues like hallucinations and name confusion 
that occur when training Transformers from scratch on small datasets.
"""

# !pip install transformers datasets rouge_score accelerate torch pandas

import os
import torch
import pandas as pd
import numpy as np
from datasets import load_dataset
from transformers import T5Tokenizer, T5ForConditionalGeneration, Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
import nltk
from nltk.tokenize import sent_tokenize
import numpy as np

# Ensure nltk resources
nltk.download('punkt')

# --- 1. Load Data ---
print("Loading Dataset...")
dataset = load_dataset("knkarthick/samsum")

# --- 2. Load Model & Tokenizer ---
MODEL_CHECKPOINT = "t5-small"
print(f"Loading {MODEL_CHECKPOINT}...")

tokenizer = T5Tokenizer.from_pretrained(MODEL_CHECKPOINT)
model = T5ForConditionalGeneration.from_pretrained(MODEL_CHECKPOINT)

# --- 3. Preprocess Data ---
prefix = "summarize: "
max_input_length = 512
max_target_length = 128

def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["dialogue"]]
    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

    # Setup the tokenizer for targets
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(examples["summary"], max_length=max_target_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

print("Preprocessing data...")
tokenized_datasets = dataset.map(preprocess_function, batched=True)

# --- 4. Metrics ---
from datasets import load_metric
rouge = load_metric("rouge")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    
    # Rouge expects a newline after each sentence
    decoded_preds = ["\n".join(sent_tokenize(pred.strip())) for pred in decoded_preds]
    decoded_labels = ["\n".join(sent_tokenize(label.strip())) for label in decoded_labels]
    
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    
    # Extract a few results
    result = {key: value.mid.fmeasure * 100 for key, value in result.items()}
    return {k: round(v, 4) for k, v in result.items()}

# --- 5. Training Arguments ---
batch_size = 8
model_name = MODEL_CHECKPOINT.split("/")[-1]
args = Seq2SeqTrainingArguments(
    f"{model_name}-finetuned-samsum",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=5, # T5 converges fast
    predict_with_generate=True,
    fp16=True, # Use FP16 if GPU supports it (Colab usually does)
    report_to="none"
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model,
    args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# --- 6. Train ---
print("Starting Training...")
trainer.train()

# --- 7. Save Model ---
trainer.save_model("t5-finetuned-samsum")
print("Model Saved to t5-finetuned-samsum")

# --- 8. Inference Test ---
print("\n--- Testing Predictions ---")
test_data = dataset['test'].select(range(5))

for i in range(len(test_data)):
    text = test_data[i]['dialogue']
    ref = test_data[i]['summary']
    
    inputs = tokenizer("summarize: " + text, return_tensors="pt", max_length=512, truncation=True).input_ids.to("cuda")
    outputs = model.generate(inputs, max_length=128, num_beams=4, length_penalty=2.0, early_stopping=True)
    pred = tokenizer.decode(outputs[0], skip_special_tokens=True)
    
    print(f"\nOriginal: {text}")
    print(f"Reference: {ref}")
    print(f"T5 Prediction: {pred}")

# Utility to zip for download
import shutil
shutil.make_archive('t5-finetuned-samsum', 'zip', 't5-finetuned-samsum')
print("Model zipped.")
